In [1]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [4]:
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [5]:
# output dataset            
y = np.array([[0,0,1,1]]).T
y

array([[0],
       [0],
       [1],
       [1]])

In [20]:
np.random.seed(1)

In [32]:
np.random.random((3,1))

array([[ 1.06633057],
       [ 1.38375423],
       [ 0.63103126]])

array([[-0.43911202],
       [ 0.57855866],
       [-0.79354799]])

In [7]:
syn0 = 2*np.random.random((3,1)) - 1

In [8]:
for iter in range(10000):

    # forward propagation
    l0 = X # layer 0
    l1 = nonlin(np.dot(l0,syn0)) # layer 1

In [10]:
l1_error = y - l1

In [11]:
l1

array([[ 0.2689864 ],
       [ 0.36375058],
       [ 0.23762817],
       [ 0.3262757 ]])

In [12]:
l1_error

array([[-0.2689864 ],
       [-0.36375058],
       [ 0.76237183],
       [ 0.6737243 ]])

In [13]:
l1_delta = l1_error * nonlin(l1,True) ##doubt
syn0 += np.dot(l0.T,l1_delta)

In [36]:
l0.T

array([[0, 0, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 1, 1]])

In [14]:
l1_delta

array([[-0.05289153],
       [-0.08418501],
       [ 0.13811206],
       [ 0.14809799]])

In [15]:
syn0

array([[ 0.12025406],
       [ 0.50456196],
       [-0.85063774]])

In [16]:
nonlin(l1,True)

array([[ 0.19663272],
       [ 0.23143609],
       [ 0.18116102],
       [ 0.21981987]])

In [39]:
np.dot(l0.T,l1_delta)

array([[ 0.28621005],
       [ 0.06391297],
       [ 0.14913351]])

In [40]:
print("Output After Training:")
print(l1)

Output After Training:
[[ 0.2689864 ]
 [ 0.36375058]
 [ 0.23762817]
 [ 0.3262757 ]]


In [ ]:
###3 layers

In [41]:

# input dataset# input  
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])

In [43]:

# output dataset            
y = np.array([[0,1,1,0]]).T
# same as y = np.array([[0],
#                       [1],
#                       [1],
#                       [0]])

In [44]:
np.random.seed(1)

In [45]:
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [47]:
syn0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [48]:
syn1

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [61]:
for iter in range(100000):

    # Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0)) # 4x3 * 3x4 = 4x4
    l2 = nonlin(np.dot(l1,syn1)) # 4x4 * 4x1 = 4x1
    if (iter% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))  ###doubt

Error:0.496410031903
Error:0.496410031903
Error:0.496410031903
Error:0.496410031903
Error:0.496410031903
Error:0.496410031903
Error:0.496410031903
Error:0.496410031903
Error:0.496410031903
Error:0.496410031903


In [62]:
l2_error = y - l2
l2_error

array([[-0.47070349],
       [ 0.51283773],
       [ 0.45888728],
       [-0.54275466]])

In [51]:
if (iter% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))  ###doubt

In [52]:
l2_delta = l2_error*nonlin(l2,deriv=True)

In [53]:
l1_error = l2_delta.dot(syn1.T)

In [54]:
l1_delta = l1_error * nonlin(l1,deriv=True)

In [55]:
syn1 += l1.T.dot(l2_delta)
syn0 += l0.T.dot(l1_delta)

In [60]:
print(l2)

[[ 0.47372957]
 [ 0.48895696]
 [ 0.54384086]
 [ 0.54470837]]
