In [74]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [75]:
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [76]:
# output dataset            
y = np.array([[0,0,1,1]]).T
y

array([[0],
       [0],
       [1],
       [1]])

In [77]:
np.random.seed(123)

In [78]:
np.random.random((3,1))

array([[ 0.69646919],
       [ 0.28613933],
       [ 0.22685145]])

array([[-0.43911202],
       [ 0.57855866],
       [-0.79354799]])

In [79]:
syn0 = 2*np.random.random((3,1)) - 1

In [80]:
for iter in range(10000):

    # forward propagation
    l0 = X # layer 0
    l1 = nonlin(np.dot(l0,syn0)) # layer 1

In [81]:
l1_error = y - l1

In [82]:
l1

array([[ 0.46162882],
       [ 0.57080857],
       [ 0.4872134 ],
       [ 0.59574826]])

In [73]:
l1_error

array([[-0.44876542, -0.51786936, -0.45919995, -0.59146586],
       [ 0.71350245,  0.67866968,  0.69025292,  0.48479854],
       [ 0.59209988,  0.37585198,  0.7626185 ,  0.50671505],
       [-0.25361036, -0.42263136, -0.14126444, -0.41676548]])

In [83]:
l1_delta = l1_error * nonlin(l1,True) ##doubt
syn0 += np.dot(l0.T,l1_delta)

In [84]:
l0.T

array([[0, 0, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 1, 1]])

In [85]:
l1_delta

array([[-0.11472753],
       [-0.13984019],
       [ 0.12811281],
       [ 0.09735686]])

In [86]:
syn0

array([[ 0.32809921],
       [ 0.39645461],
       [-0.18288513]])

In [87]:
nonlin(l1,True)

array([[ 0.24852765],
       [ 0.24498615],
       [ 0.2498365 ],
       [ 0.24083227]])

In [88]:
np.dot(l0.T,l1_delta)

array([[ 0.22546967],
       [-0.04248333],
       [-0.02909805]])

In [89]:
print("Output After Training:")
print(l1)

Output After Training:
[[ 0.46162882]
 [ 0.57080857]
 [ 0.4872134 ]
 [ 0.59574826]]


In [ ]:
###3 layers

In [90]:

# input dataset# input  
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])

In [91]:

# output dataset            
y = np.array([[0,1,1,0]]).T
# same as y = np.array([[0],
#                       [1],
#                       [1],
#                       [0]])

In [92]:
np.random.seed(123)

In [93]:
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [94]:
syn0

array([[ 0.39293837, -0.42772133, -0.54629709,  0.10262954],
       [ 0.43893794, -0.15378708,  0.9615284 ,  0.36965948],
       [-0.0381362 , -0.21576496, -0.31364397,  0.45809941]])

In [95]:
syn1

array([[-0.12285551],
       [-0.88064421],
       [-0.20391149],
       [ 0.47599081]])

In [96]:
for iter in range(1000):

    # Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0)) # 4x3 * 3x4 = 4x4
    l2 = nonlin(np.dot(l1,syn1)) # 4x4 * 4x1 = 4x1

In [98]:
l2_error = y - l2
l2_error

array([[-0.43836968],
       [ 0.55875041],
       [ 0.53324227],
       [-0.46906213]])

In [51]:
if (iter% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))  ###doubt

In [52]:
l2_delta = l2_error*nonlin(l2,deriv=True)

In [53]:
l1_error = l2_delta.dot(syn1.T)

In [54]:
l1_delta = l1_error * nonlin(l1,deriv=True)

In [55]:
syn1 += l1.T.dot(l2_delta)
syn0 += l0.T.dot(l1_delta)

In [99]:
print(l2)

[[ 0.43836968]
 [ 0.44124959]
 [ 0.46675773]
 [ 0.46906213]]


####Gradient Descent

In [4]:
import numpy as np

In [5]:
alphas = [0.001,0.01,0.1,1,10,100,1000]

In [6]:
hiddenSize = 3

In [7]:
# compute sigmoid nonlinearity
def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

In [8]:
# convert output of sigmoid function to its derivative
def sigmoid_output_to_derivative(output):
    return output*(1-output)

In [9]:
X = np.array([[0,0,1],
          [0,1,1],
          [1,0,1],
             [1,1,1]])

In [10]:
y = np.array([[0],
            [1],
            [1],
           [0]])

In [26]:
for alpha in alphas:
    print ("\nTraining With Alpha:" + str(alpha))
    np.random.seed(1)
# randomly initialize our weights with mean 0
    synapse_0 = 2*np.random.random((3,hiddenSize)) - 1
    synapse_1 = 2*np.random.random((hiddenSize,1)) - 1
    for j in range(60000):
        layer_0 = X
        layer_1 = sigmoid(np.dot(layer_0,synapse_0))
        layer_2 = sigmoid(np.dot(layer_1,synapse_1))
    # how much did we miss the target value?
        layer_2_error = layer_2 - y
        if (j% 10000) == 0:
            print ("Error after "+str(j)+"iterations:" + str(np.mean(np.abs(layer_2_error))))
        layer_2_delta = layer_2_error*sigmoid_output_to_derivative(layer_2)

# how much did each l1 value contribute to the l2 error (according to the weights)?
        layer_1_error = layer_2_delta.dot(synapse_1.T)


# were we really sure? if so, don't change too much.
        layer_1_delta = layer_1_error * sigmoid_output_to_derivative(layer_1)

        synapse_1 -= alpha * (layer_1.T.dot(layer_2_delta))
        synapse_0 -= alpha * (layer_0.T.dot(layer_1_delta))


Training With Alpha:0.001
Error after 0iterations:0.501805775005
Error after 10000iterations:0.501210638185
Error after 20000iterations:0.500789898168
Error after 30000iterations:0.500465016768
Error after 40000iterations:0.500190060259
Error after 50000iterations:0.499936422407

Training With Alpha:0.01
Error after 0iterations:0.501805775005
Error after 10000iterations:0.498295738833
Error after 20000iterations:0.476693714606
Error after 30000iterations:0.399012006685
Error after 40000iterations:0.329136314333
Error after 50000iterations:0.262578687001

Training With Alpha:0.1
Error after 0iterations:0.501805775005
Error after 10000iterations:0.169017852254
Error after 20000iterations:0.147617279981
Error after 30000iterations:0.141622169761
Error after 40000iterations:0.138612565567
Error after 50000iterations:0.136747041091

Training With Alpha:1
Error after 0iterations:0.501805775005
Error after 10000iterations:0.132686375391
Error after 20000iterations:0.0129160750845
Error after

In [20]:
synapse_1 

array([[ -4.9624094 ],
       [ -3.49226718],
       [-13.36121777]])

In [21]:
synapse_0 

array([[ 0.15086787,  0.13444312,  2.32281688],
       [-0.32103702,  0.16717063,  3.05377908],
       [-0.82701527,  0.81448705, -0.34479584]])